### ISSUE TITLE
例子运行不了

### ISSUE THREAD

**Issue by wuchuguang** [liwenzhu/bosonnlp#1]
nodejs_lib node index.js 
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND api.bosonnlp.com api.bosonnlp.com:80
    at errnoException (dns.js:27:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete](dns.js:78:26)
➜  nodejs_lib node index.js
{"status":403,"message":"malformed token format"}

**Comment by wuchuguang** [comment]
ping api.bosonnlp.com 通。
telnet api.bosonnlp.com 80 不通。

**Comment by liwenzhu** [comment]
你运行的是哪一个例子？ 我试了一下是没有问题的

**Comment by wuchuguang** [comment]
var bosonnlp = require('bosonnlp');
var nlp = new bosonnlp.BosonNLP('YOUR_API_KEY');
nlp.ner('成都商报记者 姚永忠', function (result) {
    console.log(result);
});

**Comment by liwenzhu** [comment]
提示的错误是格式错误，这个是你填写的api_key格式不对， 应该是 abc.def.hij这样的格式，如果去掉一个中间的点，就会返回{"status":403,"message":"malformed token format"}， 你再看看你的api_key是不是填错了。

**Comment by wuchuguang** [comment]
我填上我的key后再运行的。报那个错。你那边试一下。

在 2016-06-14 18:10:07，"Vincent" notifications@github.com 写道：

提示的错误是格式错误，这个是你填写的api_key格式不对， 应该是 abc.def.hij这样的格式，如果去掉一个中间的点，就会返回{"status":403,"message":"malformed token format"}， 你再看看你的api_key是不是填错了。

**Comment by liwenzhu** [comment]
我这用我的key运行没错误，把key改成一个错误的格式才报的你的那个错误，应该还是key的问题，要不你新申请一个key再看看

**Comment by wuchuguang** [comment]
正常了，谢谢。

在 2016-06-14 18:46:17，"Vincent" notifications@github.com 写道：

我这用我的key运行没错误，把key改成一个错误的格式才报的你的那个错误，应该还是key的问题，要不你新申请一个key再看看

**Comment by wuchuguang** [comment]
今日剩余500000 试用。
这是每天会刷新吗？还是试用500000次后，就只能付费了？

**Comment by liwenzhu** [comment]
这个每天都刷新。
